services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
    networks:
      - internal
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.129.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - internal
  server:
    image: chromadb/chroma:1.0.15
    volumes:
      - chroma_data:/data
    ports:
      - "8008:8008"
    networks:
      - internal
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4317/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
    depends_on:
      - otel-collector
      - zipkin
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data



  document-ai-api:
   build:
     context: .
   environment:
     - EMBEDDING_SERVICE=alibaba
     - LLM_SERVICE=qwen
     - DASHSCOPE_API_KEY=KEY_DASHSCOPE
     #- HUGGINGFACE_API_KEY=KEY
     #- GROQ_API_KEY=KEY
     - EMBEDDING_MODEL_NAME=text-embedding-v3
     - LLM_MODEL_NAME=qwen3-32b
     - DOMAIN=http://localhost:3000

     - CHROMA_HOST=server
   ports:
    - "8000:8000"
   networks:
     - internal
   depends_on:
     - server

networks:
  internal:

volumes:
  chroma_data:
  open-webui:

