FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

ARG EMBEDDING_SERVICE
ARG LLM_SERVICE
ARG EMBEDDING_MODEL_NAME
ARG LLM_MODEL_NAME
ARG CHROMA_HOST
ARG DOMAIN

# Set environment variables for configuration
ENV EMBEDDING_SERVICE=${EMBEDDING_SERVICE}
ENV LLM_SERVICE=${LLM_SERVICE}
ENV EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
ENV CHROMA_HOST=${CHROMA_HOST}
ENV LLM_MODEL_NAME=${LLM_MODEL_NAME}
ENV DOMAIN=${DOMAIN}
ENV TOKENIZERS_PARALLELISM=False

COPY . /app
WORKDIR /app

# Install dependencies
RUN uv sync --locked

CMD ["uv", "run", "--with", "gunicorn", "gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
